(** log facilities *)

(** fid of the log file *)
let logfid = ref stdout

(** open the given log file *)
let init fname =
  logfid := open_out fname

(** dump a message provided by the analysis step *)
let from_analysis msg = Printf.fprintf (!logfid) "[analysis] %s\n" msg

(** dump a message produced by the decoding step *)
let from_decoder msg = Printf.fprintf (!logfid) "[decoding] %s\n" msg
						   
(** dump a message generated by then configuration parsing step *)
let from_config msg = Printf.fprintf !logfid "[config] %s\n" msg
				     
(** close the log file *)
let close () = close_out !logfid

let error msg =
  Printf.fprintf !logfid "fatal error: %s\n" msg;
  flush stdout;
  close();
  raise (Exceptions.Error msg) 
